sudo: required
language: generic 

services:
  - docker

before_install:
  - docker login -u cseifertiz -p $DOCKER_PASSWORD
  - docker build -t cseifertiz/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true cseifertiz/react-test npm test

after_success:
  - docker build -t cseifertiz/multi-client ./client
  - docker build -t cseifertiz/multi-nginx ./nginx
  - docker build -t cseifertiz/multi-server ./server
  - docker build -t cseifertiz/multi-worker ./worker
  # Log in ot the docker CLI
  # - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker login -u cseifertiz -p $DOCKER_PASSWORD
  # Take those images and push them to docker hub
  - docker push cseifertiz/multi-client
  - docker push cseifertiz/multi-nginx
  - docker push cseifertiz/multi-server
  - docker push cseifertiz/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker'
  env: 'Multidocker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-019801468546'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
